Update Action-OFRP-Builder.yml

diff --git a/.github/workflows/Action-OFRP-Builder.yml b/.github/workflows/Action-OFRP-Builder.yml
--- a/.github/workflows/Action-OFRP-Builder.yml
+++ b/.github/workflows/Action-OFRP-Builder.yml
@@ -1,143 +1,197 @@
-# Credits to azwhikaru & chickendrop89 
- # https://github.com/azwhikaru/Action-OFRP-Builder 
-  
- name: Orangefox-build
-  
- on: 
-   workflow_dispatch: 
-     inputs: 
-       SYNC_URL: 
-         description: 'SYNC_URL' 
-         required: true 
-         default: 'https://gitlab.com/OrangeFox/sync.git' 
-       MANIFEST_BRANCH: 
-         description: 'MANIFEST_BRANCH' 
-         required: true 
-         default: '12.1' 
-       DEVICE_TREE_URL: 
-         description: 'DEVICE_TREE_URL' 
-         required: true 
-         default: 'https://github.com/Micloudtest/limer.git' 
-       DEVICE_TREE_BRANCH: 
-         description: 'DEVICE_TREE_BRANCH' 
-         required: true 
-         default: 'main' 
-       DEVICE_PATH: 
-         description: 'DEVICE_PATH' 
-         required: true 
-         default: 'device/xiaomi/merlin' 
-       DEVICE_NAME: 
-         description: 'DEVICE_NAME' 
-         required: true 
-         default: 'merlin' 
-       DEVICE_VARIANT: 
-         description: 'DEVICE_VARIANT' 
-         required: true 
-         default: 'Merlin-Recovery-Build-Beta' 
-       MAKEFILE_NAME: 
-         description: 'MAKEFILE_NAME' 
-         required: true 
-         default: 'twrp_merlin' 
-       BUILD_TARGET: 
-         description: 'BUILD_TARGET' 
-         required: true 
-         default: 'recovery' 
-  
- jobs: 
-   build: 
-     if: github.event.repository.owner.id == github.event.sender.id 
-     runs-on: ubuntu-latest 
-     permissions: 
-       contents: write 
-     steps: 
-  
-     # You might want to Checkout your repo first, but not mandatory 
-     - name: Check Out 
-       uses: actions/checkout@v3 
-  
-     # Cleanup The Actions Workspace Using Custom Composite Run Actions 
-     - name: Cleanup 
-       uses: rokibhasansagar/slimhub_actions@main 
-  
-     - name: Initialize workspace 
-       run: | 
-         mkdir workspace 
-          cd workspace 
-         echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT 
-       id: pwd 
-  
-     - name: Prepare the build environment 
-       run: | 
-         sudo apt-get install git aria2 -y 
-         git clone --depth 1 https://gitlab.com/OrangeFox/misc/scripts 
-           cd scripts 
-             sudo bash setup/android_build_env.sh 
-               sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh 
-             sudo bash setup/install_android_sdk.sh 
-       working-directory: ${{ steps.pwd.outputs.workspace-folder }} 
-  
-     - name: Sync OrangeFox sources and minimal manifest 
-       run: | 
-         cd ${{ steps.pwd.outputs.workspace-folder }} 
-         git clone --depth 1 ${{ github.event.inputs.SYNC_URL }} 
-           cd sync 
-             ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }} 
-       working-directory: ${{ steps.pwd.outputs.workspace-folder }} 
-  
-     - name: Clone device tree 
-       run: | 
-         cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }} 
-           git clone --depth 1 ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }} 
-       working-directory: ${{ steps.pwd.outputs.workspace-folder }} 
-  
-     - name: Set Swap Space 
-       uses: pierotofy/set-swap-space@master 
-       with: 
-         swap-size-gb: 12 
-  
-     - name: Set up ccache 
-       uses: hendrikmuhs/ccache-action@v1.2      
-       with:          
-         key: ${{ runner.os }}-${{ github.sha }}          
-         restore-keys: ${{ runner.os }} 
-  
-     - name: Building recovery 
-       run: | 
-         HOME_CCACHE_DIR=${{ steps.pwd.outputs.workspace-folder }}/../.ccache 
-         BIND_CCACHE_DIR=/mnt/ccache 
-  
-         echo "Creating/Binding CCACHE directories ..." 
-         if [ ! -d "$HOME_CCACHE_DIR" ]; then 
-             mkdir $HOME_CCACHE_DIR 
-         fi 
-  
-         sudo mkdir $BIND_CCACHE_DIR 
-         sudo mount --bind $HOME_CCACHE_DIR $BIND_CCACHE_DIR 
-  
-         cd ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }} 
-           set +e 
-             source build/envsetup.sh 
-           set -e 
-           lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all) 
-       working-directory: ${{ steps.pwd.outputs.workspace-folder }} 
-       continue-on-error: true 
-  
-     - name: Check the output directory before uploading 
-       run: | 
-         ls -al ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/ 
-         echo 
-         ls -al ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ 
-  
-     - name: Upload to Release 
-       uses: softprops/action-gh-release@v1 
-       with: 
-         files: | 
-           ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.img 
-           ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip 
-         name: orangefox-${{ github.event.inputs.DEVICE_VARIANT }} 
-         tag_name: ${{ github.run_id }} 
-         body: | 
-           Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }} 
-           Device: ${{ github.event.inputs.DEVICE_NAME }} 
-       env: 
-         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+name: OrangeFox - Build
+
+on:
+  workflow_dispatch:
+    inputs:
+      SYNC_URL: 
+        description: 'SYNC_URL' 
+        required: true 
+        default: 'https://gitlab.com/OrangeFox/sync.git' 
+        type: choice
+        options:
+        - https://gitlab.com/OrangeFox/sync.git
+        - https://github.com/linastorvaldz/fox-sync.git
+      MANIFEST_BRANCH:
+        description: 'OrangeFox Branch'
+        required: true
+        default: '12.1'
+        type: choice
+        options:
+        - 14.1
+        - 12.1
+        - 11.0
+      DEVICE_TREE:
+        description: 'Custom Recovery Tree'
+        required: true
+        default: 'https://github.com/kinguser981/android_device_xiaomi_marble-OFRP'
+      DEVICE_TREE_BRANCH:
+        description: 'Custom Recovery Tree Branch'
+        required: true
+        default: 'fox_12.1'
+      DEVICE_PATH:
+        description: 'Specify your device path.'
+        required: true
+        default: 'device/xiaomi/marble'
+      DEVICE_NAME:
+        description: 'Specify your Device Codename.'
+        required: true
+        default: 'marble'
+      BUILD_TARGET:
+        description: 'Specify your Build Target'
+        required: true
+        default: 'recovery'
+        type: choice
+        options:
+        - boot
+        - recovery
+        - vendorboot
+      LDCHECK:
+        description: 'Path of blobs to check' 
+        required: true
+        default: 'system/bin/qseecomd'
+
+jobs:
+  build:
+    name: Build OFRP by ${{ github.actor }}
+    runs-on: ubuntu-latest
+    if: github.event.repository.owner.id == github.event.sender.id
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    permissions:
+      contents: write
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Clean-up
+      uses: rokibhasansagar/slimhub_actions@main
+
+    - name: Swap Space
+      uses: pierotofy/set-swap-space@master
+      with:
+        swap-size-gb: 24
+      
+    - name: Build Environment
+      run: |
+       curl -LSs https://raw.githubusercontent.com/akhilnarang/scripts/refs/heads/master/setup/android_build_env.sh | bash -
+      
+    - name: Set-up Manifest
+      if: github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1' || github.event.inputs.MANIFEST_BRANCH == '14.1'
+      run: |
+        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
+        cd ${GITHUB_WORKSPACE}/OrangeFox
+        git config --global user.name "Samuel Kendall"
+        git config --global user.email "kinguser981@gmail.com" 
+        git clone ${{ github.event.inputs.SYNC_URL }}
+        cd sync
+        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+
+    - name: Clone Device Tree
+      run: |
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
+        cd ${{ github.event.inputs.DEVICE_PATH }}
+        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+
+    - name: Check Manifest Branch
+      uses: haya14busa/action-cond@v1
+      id: fox_branch
+      with:
+        cond: ${{ github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1' }}
+        if_true: lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image
+        if_false: lunch omni_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka ${{ github.event.inputs.BUILD_TARGET }}image
+      
+    - name: Building OrangeFox
+      run: |
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        set +e
+        source build/envsetup.sh
+        export ALLOW_MISSING_DEPENDENCIES=true
+        set -e
+        ${{ steps.fox_branch.outputs.value }}
+
+    - name: Set Build Date # Output will be use in Release
+      run: |
+        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
+        DEVICE_TREE_URL="${{ github.event.inputs.DEVICE_TREE }}"
+        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
+          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
+        fi
+        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV
+
+    - name: Check if Recovery Exist
+      run: |
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
+        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
+            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
+            echo "FILE_PATH=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
+            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
+            echo "FILE_PATH=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+        else
+            echo "Recovery out directory is empty."
+            cd Exit
+        fi
+
+    - name: Rename the Recovery
+      run: |
+        cd ${{ env.FILE_PATH }}/
+        if [ "${{ github.event.inputs.BUILD_TARGET }}" = "boot" ]; then
+        mv OrangeFox*.img boot.img
+        echo "RECOVERY_TYPE=boot" >> $GITHUB_ENV
+        echo "boot.img file found!"
+        elif [ "${{ github.event.inputs.BUILD_TARGET }}" = "recovery" ]; then
+        mv OrangeFox*.img recovery.img
+        echo "RECOVERY_TYPE=recovery" >> $GITHUB_ENV
+        echo "recovery.img file found!"
+        elif [ "${{ github.event.inputs.BUILD_TARGET }}" = "vendorboot" ]; then
+        mv OrangeFox*.img vendor_boot.img
+        echo "RECOVERY_TYPE=vendor_boot" >> $GITHUB_ENV
+        echo "vendor_boot.img file found!"
+        else
+        echo "No Recovery file found!"
+        fi
+      continue-on-error: true
+        
+
+    - name: Upload to Release
+      if: env.CHECK_IMG_IS_OK == 'true'
+      uses: softprops/action-gh-release@v1
+      with:
+        files: |
+          ${{ env.FILE_PATH }}/${{ env.RECOVERY_TYPE }}.img
+          ${{ env.FILE_PATH }}/OrangeFox*.zip
+        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
+        body: |
+          Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          
+    - name: Release ramdisk-recovery
+      if: env.CHECK_IMG_IS_OK == 'true'
+      uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
+      with:
+        files: |
+          ${{ env.FILE_PATH }}/obj/PACKAGING/vendor_ramdisk_fragments_intermediates/recovery.*
+          ${{ env.FILE_PATH }}/ramdisk-recovery.*
+        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
+        body: |
+          Target: ${{ env.RECOVERY_TYPE }}.img
+          Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }}) during building.
+          MD5 (img): ${{ env.MD5_IMG }}
+          
+    - name: Run LDCheck
+      run: |
+        cd tools
+        mv -n libneeds ${{ env.FILE_PATH }}/recovery/root/
+        mv -n ldcheck ${{ env.FILE_PATH }}/recovery/root/
+        cd ${{ env.FILE_PATH }}/recovery/root/
+        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ github.event.inputs.LDCHECK }}
+        echo "Done checking missing dependencies. Review, and reconfigure your tree."
+      continue-on-error: true
